In [41]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

df  = pd.read_csv("classpass.csv")
#df.tags = df.tags.fillna("unknown")
df.sample(15)

,tags,livestream,name,location,avg_rating,num_ratings
854,['barre'],False,Physique 57,"2109 Broadway, Suite 206, New York",4.8,(5000+)
196,['strength training'],False,The Body Shop Training,"119 Park Avenue, 2nd Floor, Summit",4.8,(100+)
744,['dance'],False,Dance With Me USA,"37 West 37th Street, 2nd Floor, New York",4.5,(68)
1010,['cycling'],False,CycleBar,"125 Vervalen St, Closter",4.7,(57)
749,['dance'],False,TwerkAerobics,"Ripley Grier Studios, 520 8th Avenue, 16th Flo...",4.4,(38)
387,"['personal training', 'livestream personal tra...",True,RKF Fitness Training,"4108 Carpenter Avenue, The Bronx",NaN,NaN
548,"['dance', 'livestream dance']",True,Ikigaiusa,"325 East 65th Street, New York",4.8,(19)
539,['strength training'],False,Golden Phoenix CrossFit,"Boulevard, Kenilworth",4.7,(56)
692,['strength training'],False,Haute Sculpt,"Stepping out Studios, 37 W 26th street, Floor ...",NaN,NaN
788,['strength training'],False,On the Mend Customized Fitness and Massage,"321 West 44th Street, New York",NaN,NaN
489,"['livestream hiit', 'strength training']",True,HIIT BOX,"548 Union Street, Brooklyn",4.8,(5000+)
833,['boxing'],False,Sweatbox Brooklyn,"229 46th Street, Brooklyn",4.9,(100+)
491,"['stretching', 'massage', 'livestream stretchi...",True,Racked Stretch,"28 East 4th St, New York",4.7,(500+)
673,['yoga'],False,Lyons Den Power Yoga,"267 West 17th Street 2nd Floor, New York",4.8,(1000+)
590,['cycling'],False,AQUA STUDIO,"78 Franklin St, New York",4.6,(5000+)

In [37]:
df.livestream.value_counts()

False    851
True     159
Name: livestream, dtype: int64

In [10]:
lis_tags = df.tags.dropna()
lis_tags = lis_tags.apply(eval)

In [22]:

def to_1D(series):
 return pd.Series([x for _list in series for x in _list])

taglist = to_1D(lis_tags).value_counts()
top20tag = taglist[0:20]
top20tag

strength training               363
yoga                            240
dance                           164
pilates                         123
boxing                           78
martial arts                     68
livestream yoga                  60
barre                            57
cycling                          49
livestream hiit                  40
livestream pilates               28
sports recovery                  25
running                          21
gym time                         21
massage                          19
livestream strength training     18
stretching                       18
personal training                18
acupuncture                      16
prenatal                         16
dtype: int64

In [1]:
#Funnel chart for top 20 tags
fig = px.funnel(top20tag, x=top20tag.values, y=top20tag.index,
               labels=dict(index="Tag"))
fig.show()

NameError: name 'px' is not defined